In [144]:
import pandas as pd
import numpy as np

In [52]:
df = pd.read_csv("CFP_Nepal_R2.csv",header=0, sep=';')

In [159]:
df.loc[np.array(['short_term' in answer for answer in df['Q1.i']]), 'Q1.i'] = 'short_term_shelter__tent_shelt'

In [183]:
df['District']=np.array([d.lower() for d in df['District']])

In [185]:
count_list = []
for gender in ['female','male']:
    for district in df['District'].unique():
        for Q1answer in df['Q1.i'].unique():
            if Q1answer=='n/a':
                continue
            count = ((df['Gender']==gender) & (df['District']==district) & (df['Q1.i']==Q1answer)).sum()
            count_list.append({'District' : district, 'Gender' : gender, 'Q1.i' : Q1answer, 'Count' : count})
output_df = pd.DataFrame(count_list, columns=['District', 'Gender', 'Q1.i', 'Count'])

In [199]:
output_df.sort(['District', 'Gender', 'Count'], ascending = [1,1,0], inplace=True)

In [200]:
# -- 
output_df.to_csv('rearranged_df.csv', index=False)

In [204]:
# -- open 'rearranged_df.csv'
new_df = pd.read_csv('rearranged_df.csv')

In [211]:
# -- determine 'Tag' from answer in Q1.i
def determine_tag(answer):
    if ('shelter' in answer) or ('housing' in answer) :
        return 'housing'
    elif 'water' in answer:
        return 'water'
    elif 'education' in answer:
        return 'education'
    elif 'financial' in answer:
        return 'financial'
    elif ('food' in answer) or ('seeds' in answer):
        return 'food'
    elif ('healthcare' in answer) or ('psycho' in answer) or ('sanitation' in answer):
        return 'health'
    # ...
    else:
        return None

In [212]:
# -- add 'Tag' column
new_df['Tag'] = [determine_tag(tag) for tag in new_df['Q1.i']]

In [213]:
new_df

           District  Gender                            Q1.i  Count        Tag
0         bhaktapur  female      long_term_shelter__housing     41    housing
1         bhaktapur  female  short_term_shelter__tent_shelt     11    housing
2         bhaktapur  female               financial_support      3  financial
3         bhaktapur  female                     clean_water      1      water
4         bhaktapur  female                            food      1       food
5         bhaktapur  female              toilets_sanitation      1     health
6         bhaktapur  female                      healthcare      1     health
7         bhaktapur  female                           other      0       None
8         bhaktapur  female                     livelihoods      0       None
9         bhaktapur  female             housing_inspections      0    housing
10        bhaktapur  female         psychosocial_counseling      0     health
11        bhaktapur  female                       education      0  education
12        bhaktapur  female           seeds_and_fertilizers      0       food
13        bhaktapur    male      long_term_shelter__housing     53    housing
14        bhaktapur    male  short_term_shelter__tent_shelt     21    housing
15        bhaktapur    male               financial_support      2  financial
16        bhaktapur    male             housing_inspections      2    housing
17        bhaktapur    male                      healthcare      2     health
18        bhaktapur    male                     livelihoods      1       None
19        bhaktapur    male                     clean_water      1      water
20        bhaktapur    male                       education      1  education
21        bhaktapur    male                           other      0       None
22        bhaktapur    male                            food      0       food
23        bhaktapur    male              toilets_sanitation      0     health
24        bhaktapur    male         psychosocial_counseling      0     health
25        bhaktapur    male           seeds_and_fertilizers      0       food
26          dhading  female      long_term_shelter__housing     30    housing
27          dhading  female  short_term_shelter__tent_shelt      5    housing
28          dhading  female                     clean_water      2      water
29          dhading  female              toilets_sanitation      2     health
..              ...     ...                             ...    ...        ...
334        sindhuli    male                       education      1  education
335        sindhuli    male                           other      0       None
336        sindhuli    male                            food      0       food
337        sindhuli    male           seeds_and_fertilizers      0       food
338  sindhupalchowk  female      long_term_shelter__housing     60    housing
339  sindhupalchowk  female  short_term_shelter__tent_shelt     20    housing
340  sindhupalchowk  female                       education      4  education
341  sindhupalchowk  female                      healthcare      3     health
342  sindhupalchowk  female                           other      2       None
343  sindhupalchowk  female                     livelihoods      2       None
344  sindhupalchowk  female             housing_inspections      1    housing
345  sindhupalchowk  female              toilets_sanitation      1     health
346  sindhupalchowk  female                     clean_water      0      water
347  sindhupalchowk  female               financial_support      0  financial
348  sindhupalchowk  female                            food      0       food
349  sindhupalchowk  female         psychosocial_counseling      0     health
350  sindhupalchowk  female           seeds_and_fertilizers      0       food
351  sindhupalchowk    male      long_term_shelter__housing     72    housing
352  sindhupalchowk    male  short_term_shelter__tent_shelt     10    housing
353  sindhupalchowk    male                           other      4       None
354  sindhupalchowk    male                     livelihoods      4       None
355  sindhupalchowk    male               financial_support      3  financial
356  sindhupalchowk    male              toilets_sanitation      2     health
357  sindhupalchowk    male                     clean_water      1      water
358  sindhupalchowk    male                      healthcare      1     health
359  sindhupalchowk    male                            food      0       food
360  sindhupalchowk    male             housing_inspections      0    housing
361  sindhupalchowk    male         psychosocial_counseling      0     health
362  sindhupalchowk    male                       education      0  education
363  sindhupalchowk    male           seeds_and_fertilizers      0       food

[364 rows x 5 columns]